### ISSUE TITLE
macOS fails to start wezTerm after using the configuration

### ISSUE THREAD

**Issue by saikete** [KevinSilvester/wezterm-config#3] opened 2023-06-01 11:22 UTC
As the title, mac: 13.4

**Comment by KevinSilvester** [comment] 2023-06-05 16:43
I had the same issue when I tried the config on my work laptop.

The issue is that the environment variables (such as PATH) only get redefined after a shell starts and reads its config.
So when you start `wezterm` with a shell that isn't found in `/usr/bin`, `/usr/sbin` , `/bin` `/sbin`, the program just quits.

A simple fix for this is just pointing to where your shell binary is located. For [example](https://github.com/KevinSilvester/wezterm-config/blob/61417f6e85412f7b766f5621f65af6baedf1b9d2/config/launch.lua#L20):
```lua
elseif platform.is_mac then
   options.default_prog = { '/opt/homebrew/bin/fish' }
   options.launch_menu = {
      { label = 'Bash', args = { 'bash' } },
      { label = 'Fish', args = { '/opt/homebrew/bin/fish' } },
      { label = 'Nushell', args = { '/opt/homebrew/bin/nu' } },
      { label = 'Zsh', args = { 'zsh' } },
   }
end
```

**Closed** 2023-06-05 16:49 UTC
